//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Windows.Forms;


namespace NSSNAPITest {
    
    public partial class SNAPITestForm : System.Windows.Forms.Form {
        #region fields
        /// <summary>
        /// Required designer variable.
        /// </summary>
        IContainer components = null;
        MenuStrip ms1;
        ToolStripMenuItem tsmiFile;
        ToolStripMenuItem tsmiFileExit;
        #endregion
        #region Windows Form Designer generated code
        /// <summary>Required method for Designer support</summary>
        void InitializeComponent() {
            this.ms1 = new System.Windows.Forms.MenuStrip();
            this.tsmiFile = new System.Windows.Forms.ToolStripMenuItem();
            this.tsmiTest = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
            this.tsmiFileExit = new System.Windows.Forms.ToolStripMenuItem();
            this.tsmiSetUSB = new System.Windows.Forms.ToolStripMenuItem();
            this.tsmiSetSNAPI = new System.Windows.Forms.ToolStripMenuItem();
            this.ms1.SuspendLayout();
            this.SuspendLayout();
            // 
            // ms1
            // 
            this.ms1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.tsmiFile});
            this.ms1.Location = new System.Drawing.Point(0, 0);
            this.ms1.Name = "ms1";
            this.ms1.Size = new System.Drawing.Size(284, 24);
            this.ms1.TabIndex = 0;
            this.ms1.Text = "ms1";
            // 
            // tsmiFile
            // 
            this.tsmiFile.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.tsmiSetSNAPI,
            this.tsmiSetUSB,
            this.tsmiTest,
            this.toolStripSeparator1,
            this.tsmiFileExit});
            this.tsmiFile.Name = "tsmiFile";
            this.tsmiFile.Size = new System.Drawing.Size(37, 20);
            this.tsmiFile.Text = "File";
            // 
            // tsmiTest
            // 
            this.tsmiTest.Name = "tsmiTest";
            this.tsmiTest.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.T)));
            this.tsmiTest.Size = new System.Drawing.Size(180, 22);
            this.tsmiTest.Text = "&Test";
            this.tsmiTest.Click += new System.EventHandler(this.tsmiTest_Click);
            // 
            // toolStripSeparator1
            // 
            this.toolStripSeparator1.Name = "toolStripSeparator1";
            this.toolStripSeparator1.Size = new System.Drawing.Size(177, 6);
            // 
            // tsmiFileExit
            // 
            this.tsmiFileExit.Name = "tsmiFileExit";
            this.tsmiFileExit.Size = new System.Drawing.Size(180, 22);
            this.tsmiFileExit.Text = "Exit";
            this.tsmiFileExit.Click += new System.EventHandler(this.exitClick);
            // 
            // tsmiSetUSB
            // 
            this.tsmiSetUSB.Name = "tsmiSetUSB";
            this.tsmiSetUSB.Size = new System.Drawing.Size(180, 22);
            this.tsmiSetUSB.Text = "Set USB mode";
            this.tsmiSetUSB.Click += new System.EventHandler(this.tsmiSetUSB_Click);
            // 
            // tsmiSetSNAPI
            // 
            this.tsmiSetSNAPI.Name = "tsmiSetSNAPI";
            this.tsmiSetSNAPI.Size = new System.Drawing.Size(180, 22);
            this.tsmiSetSNAPI.Text = "Set SNAPI mode";
            this.tsmiSetSNAPI.Click += new System.EventHandler(this.tsmiSetSNAPI_Click);
            // 
            // SNAPITestForm
            // 
            this.ClientSize = new System.Drawing.Size(284, 262);
            this.Controls.Add(this.ms1);
            this.MainMenuStrip = this.ms1;
            this.Name = "SNAPITestForm";
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.SNAPITestForm_FormClosed);
            this.Load += new System.EventHandler(this.formLoad);
            this.ms1.ResumeLayout(false);
            this.ms1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }
        #endregion
        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        protected override void Dispose(bool disposing) {
            if (disposing) {
                if ((components != null)) {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

         ToolStripMenuItem tsmiTest;
         ToolStripSeparator toolStripSeparator1;
         ToolStripMenuItem tsmiSetSNAPI;
         ToolStripMenuItem tsmiSetUSB;
    }
}
